package:
  name: spherical_functions
  version: '1.0'

source:
  git_url: https://github.com/moble/spherical_functions.git

build:
  detect_binary_files_with_prefix: true
  script: python setup.py install

requirements:
  build:
    - python
    - numpy >=1.7

  run:
    - python
    - numpy >=1.7
    - quaternion

about:
  home: 'https://github.com/moble/spherical_functions'
  license: MIT
  summary: 'Python/numba package for evaluating Wigner D matrices and spin-weighted spherical harmonics'
